name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    environment: expo
    steps:        
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
                  
      - name: Install dependencies
        run: npm install
      
      - name: Expo Init
        uses: expo/expo-github-action@7.2.0
        with: 
          expo-version: 5.4.3
          token: ${{ secrets.TOKEN }}
          packager: npm
          
      - name: Expo Publish app
        run: expo publish
